# Numpy 

In [117]:
list = [1,2,3,4]
list1 =[[1,2,3,4],[5,6,7,8]]

In [118]:
import numpy as np                      #For importing numy lib

In [119]:
np.array(list)                          #for creation of array 

array([1, 2, 3, 4])

In [120]:
np.array(list1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

 **<span style='color:green'> This 2 brackets indicates that it is 2d array </span>**

## **<span style='color:blue'> MORE METHOODS FOR ARRAY CREATION </span>**

In [121]:
arr = np.arange(0,10,2)                     #arange methood(start,end,step)
arr

array([0, 2, 4, 6, 8])

In [122]:
arr = np.linspace(0,10,100)                #linspace methhod(start,end,num) 
arr

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [123]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [124]:
arr= np.zeros((3,4))                     # zeros methood(nor,noc) use 2 brackets                   
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [125]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [126]:
arr = np.ones((3,4))                    #Ones Methhod(nor,noc) use 2 brackets
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [127]:
arr = np.eye(5)                        #eye methood(single input) for identity matrix Creation
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [128]:
arr = np.random.rand(4)                #rand methood(single num bcoz 1d arry creation)
arr

array([0.86590373, 0.00106576, 0.40588825, 0.80316603])

In [129]:
arr = np.random.rand(4,4)             #rand methood(nor,noc)  coz 2d array creation         
arr

array([[0.4867727 , 0.00766313, 0.74120211, 0.37226502],
       [0.33308467, 0.38964473, 0.25742679, 0.85373918],
       [0.9081192 , 0.56749924, 0.92378578, 0.21880219],
       [0.5250583 , 0.25309337, 0.68917274, 0.20335049]])

In [130]:
arr = np.random.randn(2)                       #randn Methood(single num coz 1d array Creation)
arr

array([-0.26858766,  0.14952433])

In [131]:
arr = np.random.randn(4,3)                     #randn Methood(nor,noc) 2d array creation
arr

array([[-2.16282488, -0.15721737, -0.40076853],
       [ 0.31021595,  0.74944585,  0.87819421],
       [-0.17088493, -0.25796176, -3.17566232],
       [ 1.58310623, -1.81656241,  0.50444186]])

In [132]:
arr = np.random.randint(0,50,10)               #randint Methood(low,high,num)
arr

array([40,  5, 17, 36,  4,  4, 21, 15, 28,  6])

# **<span style='color:blue'> Functions </span>**

In [133]:
arr2 = arr.reshape(5,2)                        #arrname.reshape(nor,noc)                    
arr2

array([[40,  5],
       [17, 36],
       [ 4,  4],
       [21, 15],
       [28,  6]])

In [134]:
arr2.max()                                    #arrname.max() gives max element in arr

40

In [135]:
arr2.min()                                    #arrname.min() gives max element in arr

4

In [136]:
arr2.argmax()                                 #arrname.argmax() gives the index where max element in arr                           


0

In [137]:
arr2.argmin()                                #arrname.argmin() gives the index where min element in arr

4

In [138]:
arr2.shape                                   #arrname.shape Gives shape of array

(5, 2)

In [139]:
arr2.dtype                                   #arrname.dtype Gives datatype of array                                   

dtype('int32')

# **<span style='color:blue'> Indexing & Selection </span>**

In [140]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
arr[0]

0

In [142]:
arr[10]

10

In [143]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
arr [0:5] = 100

In [145]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [146]:
arr2 = arr.copy()                    #arrname.copy() for copying array
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

* 2d Array Slicing

In [147]:
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [148]:
arr[0,2]                            #arr[which row,which column]

15

In [149]:
arr[0]                              #arr[which row] for whole row

array([ 5, 10, 15])

In [150]:
arr[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [151]:
arr[0:2,1:]

array([[10, 15],
       [25, 30]])

In [152]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [153]:
arr2 =arr[arr>5]
arr2

array([ 6,  7,  8,  9, 10])

In [154]:
a = arr>5
a

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [155]:
arr[a]

array([ 6,  7,  8,  9, 10])

# Numpy Operations:

In [156]:
arr = np.arange(0,11)        

In [157]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [158]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [159]:
np.sqrt(arr)     # give square root of array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [160]:
np.exp(arr)      # give exponant of array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [161]:
np.sin(arr)    #give sin value of arr

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])